[training_config]
pretrained_model_name_or_path = ""
vae = "/content/models/sdxl.vae.safetensors"
output_dir = "/content/output"
output_name = "hius"
max_train_epochs = 10
train_batch_size = 1
seed = 42
save_every_n_epochs = 1
mixed_precision = "bf16"
save_precision = "bf16"
sdpa = true
max_data_loader_n_workers = 2
persistent_data_loader_workers = true
gradient_checkpointing = true
highvram = true
network_train_unet_only = true
cache_latents_to_disk = true

[optimizer_config]
optimizer_type = "AdamW8bit"
optimizer_args = ""
learning_rate = 1e-5
text_encoder_lr = 1e-5
lr_scheduler = "cosine"
lr_warmup_steps = 0

[network_config]
network_dim = 32
text_encoder_lr = 1e-5
network_module = "networks.lora"
network_alpha = 32
network_args = ""

[noise_config]
noise_offset = 0.1
adaptive_noise_scale = 0.01
multires_noise_iterations = 0.3
multires_noise_discount = 6

[sample_config]
sample_every_n_steps = 400
sample_at_first = true
sample_prompts = "/content/colab_ui/config/sample_prompt.toml"

[sdxl_config]
cache_text_encoder_outputs = false
cache_text_encoder_outputs_to_disk = false

[log_config]
log_with = "tensorboard"
wandb_api_key = ""
logging_dir = "/content/colab_ui/logs"
wandb_run_name = ""

[advanced_config]
metadata_title = ""
metadata_author = ""
metadata_description = "support by lahteam.vn"
training_comment = "support by lahteam.vn"
resume = ""
save_state = false

[dataset_config]
train_data_dir = ""
reg_data_dir = ""
caption_extension = ".txt"
num_repeats = 10
flip_aug = false
keep_tokens = 0
